**Numpy**

In [1]:
import numpy as np

In [2]:
arr1 = np.arange(0, 15, 3, dtype='int') 
arr1

array([ 0,  3,  6,  9, 12])

In [3]:
arr2 = np.linspace(0, 10, num=4, dtype='int', endpoint=False)
arr2

array([0, 2, 5, 7])

In [4]:
a = np.linspace(0,20, 10, endpoint=False, dtype='int')
a

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [12]:
arr3 = np.array([5, 8, 12])
print(arr3)

[ 5  8 12]


In [7]:
arr3.shape

(3,)

In [12]:
arr4 = np.arange(5, 14, 2)

print(arr4)

[ 5  7  9 11 13]


In [8]:
arr5 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arr5)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [10]:
arr5.shape

(3, 4)

In [11]:
arr6 = np.zeros((3,4), dtype=float)
print(arr6)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [16]:
# create a 2D array with shape (3, 4)
shape = (3, 4)
arr7 = np.ones(shape, dtype='int')
print(arr7)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [17]:
# create a 2D array with shape (3, 4)
arr8 = np.empty((3,4), dtype=int)
print(arr8)

[[      2939742534936                  50                   0
                    0]
 [  29555310641283072 7146768841584043371 3257569520544657716
  4063148658377777765]
 [3975888164340968803 3990863481760080694 8386112019186069602
  3544951258285634421]]


In [18]:
# create a 3D array with shape (2, 3, 4)
nested_list = [[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],

[[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]

arr9 = np.array(nested_list)

print(arr9)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [19]:
arr9.shape

(2, 3, 4)

In [20]:
# create a 3D array with shape (2, 3, 4)
shape = (2, 3, 4)

arr11 = np.zeros(shape, dtype='int')

print(arr11)

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]


In [21]:
# create a 3D array with shape (2, 3, 4)
shape = (3, 2, 4)

arr12 = np.ones(shape, dtype='int')

print(arr12)

[[[1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]]]


In [22]:
# create a 3D array with shape (2, 3, 4)
shape = (2, 2, 4)

arr13 = np.empty(shape, dtype='int')

print(arr13)

[[[25895968444448860 23925768161198147 32370111954616435
   30681201962451036]
  [12948244072890473 32651616996819049 25896170311057512
   28710924373327984]]

 [[26740556586287209 27303510834217060 25896196080664693
   32651591226556520]
  [12948368627204207 29555336418492531 29836540811477108
   30962737072111727]]]


In [23]:
random_numbers = np.random.rand(3,3)  # Generates a 2x3 array of random numbers between 0 and 1
random_numbers

array([[0.41371236, 0.67211894, 0.29177303],
       [0.69231484, 0.56554084, 0.50765447],
       [0.06018599, 0.2490662 , 0.49719274]])

In [24]:
random_numbers = np.random.randn(2, 3)  # Generates a 2x3 array of random numbers from a standard normal distribution
random_numbers

array([[-0.45932605, -1.53868435,  0.87570512],
       [ 0.24617333, -0.00736535, -0.20847847]])

In [25]:
random_integers = np.random.randint(-10, 10, size=(2, 3))  # Generates a 2x3 array of random integers between 1 (inclusive) and 10 (exclusive)
random_integers

array([[ -1,  -7,  -9],
       [-10,  -1,   3]], dtype=int32)

In [26]:
b = np.array([2,4,56,422,32,1])
b

array([  2,   4,  56, 422,  32,   1])

In [27]:
#to find the type
type(b)

numpy.ndarray

In [28]:
i = np.identity(2) #indentity matrix is that diagonal items will be ones and evrything will be zeros
i

array([[1., 0.],
       [0., 1.]])

In [29]:
diagonal_matrix = np.diag([1, 2, 3])
print(diagonal_matrix)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [196]:
np.diag([1,2])

array([[1, 0],
       [0, 2]])

In [30]:
x = np.array([1,2,3])
y = x 
z = np.copy(x)
print(x,y,z)


[1 2 3] [1 2 3] [1 2 3]


#### **Changing the type of the data type**

In [197]:
c = np.array([11,23,44], dtype = float)
c

array([11., 23., 44.])

In [203]:
g = c.astype('int')
g

array([11, 23, 44])

In [202]:
type(g[0])

numpy.int64

In [33]:
d = np.linspace(2,10,num=8, dtype=float)
d.astype(int)

array([ 2,  3,  4,  5,  6,  7,  8, 10])

#### **Reshape**
- Both of number products should be equal to umber of Items present inside the array.

In [204]:
re = np.arange(1,11)
re

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [207]:
re.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [36]:
re1 = np.arange(1,13).reshape(3,4)
re1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [37]:
re2 = np.arange(0,8).reshape(2,2,2)
re2

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

#### **Shape**
- gives each item consist of no.of rows and np.of column

In [208]:
sh = np.arange(1,11).reshape(5,2)
sh.shape

(5, 2)

In [209]:
sh.size

10

In [210]:
sh

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [39]:
sh1 = np.arange(10)
sh1.shape

(10,)

In [40]:
sh2 = np.arange(8).reshape(2,2,2)
sh2.shape

(2, 2, 2)

#### **Size**
- gives number of items

In [41]:
si = np.arange(1,11).reshape(5,2)
si.size

10

In [42]:
len(si) # No of rows

5

#### **ItemSize**
- Memory occupied by the item

In [43]:
its = np.arange(1,13).reshape(4,3)
print(its)
its.itemsize #Memory occupied by the item

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


8

In [44]:
its1 = np.linspace(0,10, num=10)
its1.itemsize

8

### **Array Operations:**
- NumPy supports element-wise operations on arrays. Basic arithmetic operations like addition, subtraction, multiplication, and division are performed element-wise.

#### **Scalr Operation**
- Scalar operations on Numpy arrays include performing addition or subtraction, or multiplication on each element of a Numpy array.

In [45]:
import numpy as np
so = np.arange(12).reshape(3,4)

In [46]:
so

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [47]:
so + 2 # -, *, /, **, %.

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [48]:
so - 2

array([[-2, -1,  0,  1],
       [ 2,  3,  4,  5],
       [ 6,  7,  8,  9]])

In [49]:
so * 2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [50]:
so % 2

array([[0, 1, 0, 1],
       [0, 1, 0, 1],
       [0, 1, 0, 1]])

In [51]:
ml = np.array([1,2,3,4,5,6,7,8,9,10])
ml1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
np.multiply(ml,ml1)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [52]:
np.divide(ml,ml1)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### **Relational Operation**
- The relational operators are also known as comparison operators, their main function is to return either a true or false based on the value of operands.

In [211]:
ro = np.arange(12,24).reshape(3,4)
ro

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [213]:
ro > 20

array([[False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True]])

In [212]:
ro[ro > 20]

array([21, 22, 23])

In [55]:
ro[ro != 20]

array([12, 13, 14, 15, 16, 17, 18, 19, 21, 22, 23])

### **Logical Operator**

In [56]:
lo = np.array([[-1,2,7]])
lo1 = np.array([[4,5,6]])

comp = lo>lo1
comp

array([[False, False,  True]])

In [57]:
lo2 = np.array([True, False, True, False])
lo3 = np.array([True, True,False, False])

_and = np.logical_and(lo2, lo3)

_or = np.logical_or(lo2, lo3)
_and,_or

(array([ True, False, False, False]), array([ True,  True,  True, False]))

In [58]:
arr1 = np.array([1, 3, 7])
arr2 = np.array([2, 3, 6])

# Logical AND where both conditions are True (e.g., arr1 > 2 and arr2 > 2)
result_and = np.logical_and(arr1 > 2, arr2 > 2)
print(result_and)

# Logical OR where either condition is True (e.g., arr1 > 2 or arr2 > 2)
result_or = np.logical_or(arr1 > 2, arr2 > 2)
print(result_or)

[False  True  True]
[False  True  True]


#### **Vector Operation**
- We can apply on both numpy array

In [59]:
vo = np.array([1, 2, 3]) + 5
vo1 = np.array([4, 5, 6])

addition = vo + vo1
subtraction = vo - vo1
multiplication = vo * vo1
division = vo / vo1

print(vo)
print(addition,subtraction, multiplication, division)

[6 7 8]
[10 12 14] [2 2 2] [24 35 48] [1.5        1.4        1.33333333]


In [60]:
za = np.arange(12).reshape(3,4)
zb = np.arange(12, 24).reshape(3,4)
za, zb

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]))

In [61]:
addition = za + zb
subtraction = za - zb
multiplication = za * zb
print("Addition:\n", addition, "\n")

Addition:
 [[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]] 



### **Array Function**

In [214]:
Ao = np.random.random((3,3))
Ao

array([[0.62449793, 0.70274815, 0.62781062],
       [0.59782948, 0.51592789, 0.25898947],
       [0.88667881, 0.86769168, 0.12901756]])

In [215]:
Ao*100

array([[62.44979328, 70.27481481, 62.78106202],
       [59.78294773, 51.5927892 , 25.89894703],
       [88.66788117, 86.7691678 , 12.90175629]])

In [216]:
Ao = np.round(Ao*100)
Ao.astype('int')

array([[62, 70, 63],
       [60, 52, 26],
       [89, 87, 13]])

In [218]:
aa1 = np.sum(Ao, axis=0) #axis=1 represents rows , 0-columns
aa1

array([211., 209., 102.])

In [220]:
a1 = np.max(Ao)

# if we want maximum of every row
a11 = np.max(Ao, axis=1)

# # maximum of every column
a22 = np.min(Ao, axis=0)

a2 = np.min(Ao)

a3 = np.prod(Ao) #Multiplication


a1, a11, a22, a2, a3

(np.float64(89.0),
 array([70., 60., 89.]),
 array([60., 52., 13.]),
 np.float64(13.0),
 np.float64(2232599548233600.0))

### **Statistics Function**

In [221]:
St = np.random.random((3,3))
St

array([[0.95188622, 0.14953209, 0.93735048],
       [0.7254476 , 0.67332643, 0.20445053],
       [0.27838261, 0.70525823, 0.09722865]])

In [67]:
avg = np.sum(St)/np.size(St)
np.round(avg, 2)

np.float64(0.46)

In [68]:
b1 = np.mean(St)

# mean of every column
b11 = St.mean(axis=0)

b2 = np.median(St)

#median of every row
b22 = np.median(St, axis=1)

b3 = np.var(St)

b4 = np.std(St)

b1, b11, b2, b22, b3, b4

(np.float64(0.4603825903040616),
 array([0.77869016, 0.31121198, 0.29124564]),
 np.float64(0.601517148389547),
 array([0.15127235, 0.60151715, 0.73887156]),
 np.float64(0.10365804352433765),
 np.float64(0.32195969239073646))

In [69]:
np.sqrt(b3)

np.float64(0.32195969239073646)

#### **Trignometric Finction**

In [71]:
tf = np.arange(24, 36).reshape(3,4)
tf1 = np.arange(36,48).reshape(4,3)
tf

array([[24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35]])

In [ ]:
np.sin(tf)

array([[-0.90557836, -0.13235175,  0.76255845,  0.95637593],
       [ 0.27090579, -0.66363388, -0.98803162, -0.40403765],
       [ 0.55142668,  0.99991186,  0.52908269, -0.42818267]])

In [72]:
np.cos(tf)

array([[ 0.42417901,  0.99120281,  0.64691932, -0.29213881],
       [-0.96260587, -0.74805753,  0.15425145,  0.91474236],
       [ 0.83422336, -0.01327675, -0.84857027, -0.90369221]])

In [73]:
np.tan(tf)

array([[ -2.1348967 ,  -0.13352641,   1.17875355,  -3.2737038 ],
       [ -0.2814296 ,   0.88714284,  -6.4053312 ,  -0.44169557],
       [  0.66100604, -75.3130148 ,  -0.62349896,   0.47381472]])

In [74]:
a = np.sin(180)
b = np.cos(45)
c= np.tan(45)

sec = 1/a
cosec = 1/b
cot = 1/np.tan(45)

sec

np.float64(-1.2482015977941976)

#### **Log and Exponent**

In [75]:
np.log(100)

np.float64(4.605170185988092)

In [76]:
np.exp(10)

np.float64(22026.465794806718)

In [77]:
np.sqrt(25)

np.float64(5.0)

In [223]:
np.power(2,3)

np.int64(8)

In [224]:
arr4 = np.array([10, 20, 30, 40, 50])
sqrt_result = np.sqrt(arr4)
print(sqrt_result)

[3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]


#### **round**
The `numpy.round()` function rounds the elements of an array to the nearest integer or to the specified number of decimals.

In [80]:
# Round to the nearest integer
arr = np.array([1.253, 2.753, 3.553, 4.953])
rounded_arr = np.round(arr,2)
print(rounded_arr) 

[1.25 2.75 3.55 4.95]


In [225]:
np.round(75.391, 2)

np.float64(75.39)

In [81]:
# Round to two decimals
arr = np.array([1.234, 2.567, 3.891])
rounded_arr = np.round(arr, decimals=2)
print(rounded_arr)

[1.23 2.57 3.89]


#### **Floor**
The `numpy.floor()` function returns the largest integer less than or equal to each element of an array.


In [82]:
# Floor operation
arr = np.array([1.2, 2.7, 3.5, 4.9])
floored_arr = np.floor(arr)
print(floored_arr)

[1. 2. 3. 4.]


In [83]:
np.floor(np.random.random((2,3))*100) # gives the smallest integer

array([[68., 85., 34.],
       [57., 84., 33.]])

#### **Ceil**
The `numpy.ceil()` function returns the smallest integer greater than or equal to each element of an array.


In [84]:
arr = np.array([1.2, 2.7, 3.5, 4.9])
ceiled_arr = np.ceil(arr)
print(ceiled_arr)

[2. 3. 4. 5.]


In [85]:
np.ceil(np.random.random((2,3))*100) # gives highest integer

array([[52., 24., 76.],
       [23., 32., 69.]])

### **Set functions**
- `np.union1d`
- `np.intersect1d`
- `np.setdiff1d`

In [86]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

In [87]:
np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [88]:
np.intersect1d(m,n)

array([3, 4, 5])

In [89]:
# Set difference
np.setdiff1d(m,n)

array([1, 2])

### **Indexing and Slicing:**
You can access and modify elements of arrays using indexing and slicing. Indexing starts at 0, and slicing allows you to extract portions of arrays.

In [226]:
import numpy as np

idx = np.array([10, 20, 30, 40, 50])
first_element = idx[2]
sub_array = idx[1:4]
a = idx[-1]
first_element,sub_array,a

(np.int64(30), array([20, 30, 40]), np.int64(50))

In [91]:
p1 = np.arange(10)
p2 = np.arange(12).reshape(3,4)
p3 = np.arange(8).reshape(2,2,2)

In [92]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [93]:
p2[:,2]

array([ 2,  6, 10])

In [94]:
p2[:3:2, :]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [95]:
p3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [96]:
# :Here 3D is consists of 2 ,2D array , so Firstly we take 1 because our desired is 5 is in second matrix which is 1 .and 1 row so 0 and second column so 1
print(p3[1,0,1])

#Here first we take 0 because our desired is 0, is in first matrix which is 0 . and 1 row so 0 and first column so 0
p3[0,1,0]

5


np.int64(2)

In [97]:
p1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [98]:
p1[2:5]

array([2, 3, 4])

In [99]:
p1[2:5:2]

array([2, 4])

In [100]:
# fetching total First row
p2[0, :]

array([0, 1, 2, 3])

In [101]:
# fetching total third column
p2[:,2]

array([ 2,  6, 10])

In [102]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [103]:
p2[::2, ::3]

array([[ 0,  3],
       [ 8, 11]])

In [104]:
#3D Slicing
p3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [105]:
p3[0,1,:] 

array([2, 3])

In [106]:
p3[1,:,1]

array([5, 7])

#### **Isin**
- we can see that one array having values are checked in a different numpy array having different elements with different sizes.

In [107]:
import numpy as np
i = np.array([10,20,30,110])
items = [10,20,30,40,50,60,70,80,90,100]
np.isin(i,items)

array([ True,  True,  True, False])

In [108]:
i[np.isin(i,items)]

array([10, 20, 30])

In [109]:
np.isin(10, items)

array(True)

In [110]:
# Create a 2D array
arr = np.array([[1, 3, 5],[8, 2, 4]]).reshape(3, 2)

print(arr)

# Find the index of the maximum value in the entire array
max_index = np.argmax(arr)
print("Index of maximum value:", max_index)

# Find the indices of the maximum values along each column
max_indices_col = np.argmax(arr, axis=1)
print("Indices of maximum values along each column:", max_indices_col)

[[1 3]
 [5 8]
 [2 4]]
Index of maximum value: 3
Indices of maximum values along each column: [1 1 1]


In [111]:
import numpy as np

# Create a 2D array
arr = np.array([[1, 3, 5],
                [8, 2, 4]]).reshape(2, 3)

print(arr)

# Find the index of the minimum value in the entire array
min_index = np.argmin(arr)
print("Index of minimum value:", min_index)

# Find the indices of the minimum values along each row
min_indices_row = np.argmin(arr, axis=1)
print("Indices of minimum values along each row:", min_indices_row)

[[1 3 5]
 [8 2 4]]
Index of minimum value: 0
Indices of minimum values along each row: [0 1]


### **Array Methods**

#### **`np.where`**
The numpy.where() function returns the indices of elements in an input array where the given
condition is satisfied.

In [112]:
wh = np.arange(1,101)
print(wh)
np.where(wh>50)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


(array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
        67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
        84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]),)

In [113]:
# replace all values > 50 with 0
np.where(wh>50,1,wh)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1])

#### **Itrating**

In [114]:
p1 = np.arange(10)

for i in p1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [115]:
p2 = np.arange(12).reshape(3,4)

for i in p2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [116]:
p2 = np.arange(12).reshape(3,4)

## Looping on 2D array
for i in p2:
    for j in i:
        print(j)

0
1
2
3
4
5
6
7
8
9
10
11


In [117]:
for i in np.nditer(p2):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [118]:
p3 = np.arange(8).reshape(2,2,2)

## Looping on 2D array
for i in p3:
    for j in i:
        print(j)

[0 1]
[2 3]
[4 5]
[6 7]


In [119]:
for i in p3:
    for j in i:
        for k in j:
            print(k)

0
1
2
3
4
5
6
7


In [120]:
for i in np.nditer(p3):
    print(i)

0
1
2
3
4
5
6
7


print all items in 2D & 3D using nditer ----> first convert in to 1D and applying Loop

In [121]:
p4 = np.arange(12,24).reshape(3,4)
p4

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [122]:
for i in np.nditer(p4):
    if i % 2 == 0:
        print(i)

12
14
16
18
20
22


#### **Sorting**

In [123]:
s = np.random.randint(1,100,15)
s1 = np.random.randint(1,100,24).reshape(6,4)
s , s1

(array([88, 47, 64, 24, 24,  9, 46, 11, 60, 99, 34, 45,  6, 28, 19],
       dtype=int32),
 array([[35, 83,  3, 11],
        [40, 83, 70, 52],
        [42, 48, 22, 80],
        [11,  9, 85, 10],
        [ 8, 46, 43, 50],
        [80, 44, 14, 68]], dtype=int32))

In [124]:
g = np.sort(s)
g

array([ 6,  9, 11, 19, 24, 24, 28, 34, 45, 46, 47, 60, 64, 88, 99],
      dtype=int32)

In [125]:
np.sort(s)[::-1] #Descending

array([99, 88, 64, 60, 47, 46, 45, 34, 28, 24, 24, 19, 11,  9,  6],
      dtype=int32)

In [126]:
np.sort(s1)

array([[ 3, 11, 35, 83],
       [40, 52, 70, 83],
       [22, 42, 48, 80],
       [ 9, 10, 11, 85],
       [ 8, 43, 46, 50],
       [14, 44, 68, 80]], dtype=int32)

In [127]:
np.sort(s1, axis=0) #Column wise sorting

array([[ 8,  9,  3, 10],
       [11, 44, 14, 11],
       [35, 46, 22, 50],
       [40, 48, 43, 52],
       [42, 83, 70, 68],
       [80, 83, 85, 80]], dtype=int32)

#### **Append**

In [128]:
np.append(s1,1)

array([35, 83,  3, 11, 40, 83, 70, 52, 42, 48, 22, 80, 11,  9, 85, 10,  8,
       46, 43, 50, 80, 44, 14, 68,  1])

In [129]:
np.ones((4,1), dtype=int)

array([[1],
       [1],
       [1],
       [1]])

In [130]:
# adding one row to 2d arrary
np.append(s1,np.ones((6,1))).astype('int')

array([35, 83,  3, 11, 40, 83, 70, 52, 42, 48, 22, 80, 11,  9, 85, 10,  8,
       46, 43, 50, 80, 44, 14, 68,  1,  1,  1,  1,  1,  1])

#### **`np.unique`**

In [131]:
# code
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [132]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

#### **Dot Product**
`np.dot`

In [133]:
dp = np.array([[1,2],[3,4]])
dp1 = np.array([[5,6],[7,8]])
print(dp)
print(dp1)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [134]:
c = np.dot(dp,dp1)
c

array([[19, 22],
       [43, 50]])

In [135]:
A = np.array([[11, 12], [13, 14]])
B = np.array([[15, 16], [17, 18]])
dot_product = np.dot(A, B)
dot_product

array([[369, 392],
       [433, 460]])

#### **Percentaile**
- `numpy.percentile()` function used to compute the nth percentile of the given data (array elements) along the specified axis

In [227]:
s = np.array([90,10,20,30,40,50,60,70,80,100])
np.percentile(s, 100)

np.float64(100.0)

In [228]:
a = np.random.randint(1,100,16)
b = np.random.randint(1,100,24).reshape(6,4)

In [229]:
np.sort(a)

array([17, 26, 29, 32, 38, 43, 43, 44, 44, 54, 72, 75, 81, 86, 88, 93],
      dtype=int32)

In [232]:
np.percentile(a,100) #max

np.float64(93.0)

In [233]:
np.percentile(a,0) # min

np.float64(17.0)

In [234]:
np.percentile(a,50) #median

np.float64(44.0)

In [142]:
np.percentile(a,25) 

np.float64(36.0)

In [143]:
np.percentile(a,75) 

np.float64(77.5)

#### **Flip**
- The `numpy.flip()` function reverses the order of array elements along the specified axis, preserving the shape of the array.

In [144]:
fl = np.random.randint(1,100,16)
fl

array([63, 22, 77, 64, 72, 11, 74, 36, 76,  6, 31, 52, 67, 21,  8, 36],
      dtype=int32)

In [145]:
np.flip(fl)

array([36,  8, 21, 67, 52, 31,  6, 76, 36, 74, 11, 72, 64, 77, 22, 63],
      dtype=int32)

In [146]:
fl1 = np.random.randint(1,100,24).reshape(6,4)
fl1

array([[ 8, 46, 84, 92],
       [68, 87, 27, 57],
       [29, 11, 30, 46],
       [66, 92, 92, 32],
       [74, 31,  3, 39],
       [48, 98, 51, 85]], dtype=int32)

In [147]:
np.flip(fl1,axis=0)

array([[48, 98, 51, 85],
       [74, 31,  3, 39],
       [66, 92, 92, 32],
       [29, 11, 30, 46],
       [68, 87, 27, 57],
       [ 8, 46, 84, 92]], dtype=int32)

#### **Delete**
The `numpy.delete()` function returns a new array with the deletion of sub-arrays along with the mentioned axis.

In [148]:
de = np.random.randint(1,100,15)
de

array([74, 27, 51, 63, 35, 76, 81, 16, 22, 43, 37, 40, 32, 14, 87],
      dtype=int32)

In [149]:
np.delete(de,0)

array([27, 51, 63, 35, 76, 81, 16, 22, 43, 37, 40, 32, 14, 87],
      dtype=int32)

In [150]:
np.delete(de,[0,2,4]) # deleted 0,2,4 index items

array([27, 63, 76, 81, 16, 22, 43, 37, 40, 32, 14, 87], dtype=int32)

In [151]:
de

array([74, 27, 51, 63, 35, 76, 81, 16, 22, 43, 37, 40, 32, 14, 87],
      dtype=int32)

In [152]:
np.delete(de, [0,4])

array([27, 51, 63, 76, 81, 16, 22, 43, 37, 40, 32, 14, 87], dtype=int32)

### **Array Manipulation:**
You can reshape arrays using `np.reshape()`, flatten them using `np.flatten()` or `np.ravel()`, and transpose them using `np.transpose()` or array attributes.

Transpose ---> Converts rows in to clumns ad columns into rows

In [153]:
am = np.arange(12).reshape(3,4)
am

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [154]:
np.transpose(am)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [155]:
am.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [156]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
transposed_arr = np.transpose(arr)
arr,transposed_arr

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[1, 4],
        [2, 5],
        [3, 6]]))

#### **Ravel**
Converting any dimensions to 1D

In [157]:
ra = np.arange(12).reshape(3,4)
ra

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [158]:
ra.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [159]:
ra1 = np.arange(0,8).reshape(2,2,2)
ra1

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [160]:
np.ravel(ra1)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [161]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
flattened_arr = arr.flatten()
flattened_arr

array([1, 2, 3, 4, 5, 6])

In [162]:
ra.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [163]:
ra1.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7])

#### **Inverse of Array**

In [164]:
#To invert (or find the inverse of) a NumPy array, you can use the numpy.linalg.inv()
import numpy as np

# Create a square matrix (2x2 for example)
matrix = np.array([[4, 7],
                   [2, 6]])

# Calculate the inverse
inverse_matrix = np.linalg.inv(matrix)

# Print the original and inverse matrices
print("Original Matrix:")
print(matrix)

print("\nInverse Matrix:")
print(inverse_matrix)

Original Matrix:
[[4 7]
 [2 6]]

Inverse Matrix:
[[ 0.6 -0.7]
 [-0.2  0.4]]


#### **Array Concatenation** 
You can combine arrays using functions like `np.concatenate()`, `np.vstack()`, and `np.hstack()`.

In [165]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[5,6,4],[5,6,1]])
print(arr)
print(arr2)
concate = np.concatenate((arr,arr2),axis=1)
concate

[[1 2 3]
 [4 5 6]]
[[5 6 4]
 [5 6 1]]


array([[1, 2, 3, 5, 6, 4],
       [4, 5, 6, 5, 6, 1]])

#### **Stacking**
Stacking is the concept of joining arrays in NumPy. Arrays having the same dimensions can be stacked

In [166]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

vertical_stack = np.vstack((arr1, arr2))
horizantal_stack = np.hstack((arr1, arr2))
vertical_stack,horizantal_stack
# assingment : create an example for -> hstack, spilt, vsplit &hsplit

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([1, 2, 3, 4, 5, 6]))

In [167]:
w1 = np.arange(12).reshape(3,4)
w2 = np.arange(12,24).reshape(3,4)
print(w1)
print(w2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [168]:
np.hstack((w1,w2))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [169]:
np.vstack((w1,w2))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

#### **Splitting:**
- its opposite of Stacking
- Splitting arrays can be done with `np.split()`, `np.vsplit()`, and `np.hsplit()`.

In [170]:
arr1 = np.array([1,2,3,4,5,6])
splitting = np.split(arr1, 3)
splitting

[array([1, 2]), array([3, 4]), array([5, 6])]

In [171]:
w1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [172]:
np.hsplit(w1,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [173]:
np.vsplit(w2,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]

In [174]:
sp = np.array([[1,3,6],[5,8,9],[5,5,6]])
sp

array([[1, 3, 6],
       [5, 8, 9],
       [5, 5, 6]])

In [175]:
np.hsplit(sp,3)

[array([[1],
        [5],
        [5]]),
 array([[3],
        [8],
        [5]]),
 array([[6],
        [9],
        [6]])]

In [176]:
np.vsplit(sp,3)

[array([[1, 3, 6]]), array([[5, 8, 9]]), array([[5, 5, 6]])]

### **Boolean Indexing and Fancy Indexing:**
It allows you to select elements from an array based on a Boolean condition. This allows you to extract only the elements of an array that meet a certain condition, making it easy to perform operations on specific subsets of data.

In [177]:
arr = np.array([10, 20, 30, 40, 50])
bool_idx = arr > 25
print(bool_idx)
selected_elements = arr[bool_idx]

indices = np.array([0, 2, 4])
fancy_selected = arr[indices]

selected_elements,fancy_selected


[False False  True  True  True]


(array([30, 40, 50]), array([10, 30, 50]))

In [178]:
G = np.random.randint(1,100,24).reshape(6,4)
G

array([[27, 26, 35, 63],
       [40,  2, 21, 75],
       [10, 67, 15,  1],
       [79, 71, 80, 91],
       [39, 91,  5, 75],
       [58, 98, 73, 80]], dtype=int32)

In [179]:
G > 50

array([[False, False, False,  True],
       [False, False, False,  True],
       [False,  True, False, False],
       [ True,  True,  True,  True],
       [False,  True, False,  True],
       [ True,  True,  True,  True]])

In [180]:
# Where is True , it gives result , everything other that removed.
G[G > 50]

array([63, 75, 67, 79, 71, 80, 91, 91, 75, 58, 98, 73, 80], dtype=int32)

In [181]:
G % 2 == 0

array([[False,  True, False, False],
       [ True,  True, False, False],
       [ True, False, False, False],
       [False, False,  True, False],
       [False, False, False, False],
       [ True,  True, False,  True]])

In [182]:
# find out even numbers
G[G % 2 == 0]

array([26, 40,  2, 10, 80, 58, 98, 80], dtype=int32)

In [183]:
# find all numbers greater than 50 and are even
G[(G > 50) & (G % 2 == 0)] 

array([80, 58, 98, 80], dtype=int32)

In [184]:
# Result
G[~(G % 7 == 0)] # (~) = Not

array([27, 26, 40,  2, 75, 10, 67, 15,  1, 79, 71, 80, 39,  5, 75, 58, 73,
       80], dtype=int32)

In [185]:
G

array([[27, 26, 35, 63],
       [40,  2, 21, 75],
       [10, 67, 15,  1],
       [79, 71, 80, 91],
       [39, 91,  5, 75],
       [58, 98, 73, 80]], dtype=int32)

In [186]:
G[np.array([0, 2, 4])]

array([[27, 26, 35, 63],
       [10, 67, 15,  1],
       [39, 91,  5, 75]], dtype=int32)

### **Array Broadcasting:**
Broadcasting allows you to perform operations between arrays of different shapes. 

NumPy automatically handles shape compatibility by replicating values along dimensions as needed. This is particularly useful for operations that involve arrays of different shapes.

In [187]:
# Scalar and Array Broadcasting
scalar = 5
array = np.array([1, 2, 3, 4, 5])
result_scalar_array = scalar * array
result_scalar_array

array([ 5, 10, 15, 20, 25])

In [188]:
# Arrays of Different Shapes
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([10, 20, 30])
result_broadcasting = arr1 * arr2
arr1.shape,arr2.shape,result_broadcasting

((2, 3),
 (3,),
 array([[ 10,  40,  90],
        [ 40, 100, 180]]))

### **File I/O with NumPy:**
You can save and load arrays to/from files using np.save() and np.load(). For instance:

In [189]:
arr = np.array([[1, 2, 3],[4,5,6]])
np.save('my_array.npy', arr)

In [190]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [191]:
loaded_arr = np.load('my_array.npy')
loaded_arr

array([[1, 2, 3],
       [4, 5, 6]])

In [192]:
loaded_arr[loaded_arr % 2==0]

array([2, 4, 6])