**Numpy**

In [1]:
import numpy as np

In [2]:
arr1 = np.arange(0, 15, 3, dtype='int') 
arr1

array([ 0,  3,  6,  9, 12])

In [3]:
arr2 = np.linspace(0, 10, num=4, dtype='int', endpoint=False)
arr2

array([0, 2, 5, 7])

In [4]:
a = np.linspace(0,20, 10, endpoint=False, dtype='int')
a

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [5]:
arr3 = np.array([5, 8, 12])
print(arr3)

[ 5  8 12]


In [6]:
arr3.shape

(3,)

In [7]:
arr4 = np.arange(5, 14, 2)

print(arr4)

[ 5  7  9 11 13]


In [8]:
arr5 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arr5)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [9]:
arr5.shape

(3, 4)

In [10]:
arr6 = np.zeros((3,4), dtype=float)
print(arr6)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [11]:
shape = (3, 4)
arr7 = np.ones(shape, dtype='int')
print(arr7)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [12]:
# create a 2D array with shape (3, 4)
arr8 = np.empty((3,4), dtype=int)
print(arr8)

[[      2282717197784                  57                   0
                    0]
 [  29555310641283072 3976234703915214187 3256774543573148472
  4121413978593245493]
 [3759768127867530550 7089287274717132645 7162263158368055606
  8462385098680267893]]


In [13]:
# create a 3D array with shape (2, 3, 4)
nested_list = [[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],

[[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]

arr9 = np.array(nested_list)

print(arr9)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [14]:
arr9.shape

(2, 3, 4)

In [15]:
# create a 3D array with shape (2, 3, 4)
shape = (2, 3, 4)

arr11 = np.zeros(shape, dtype='int')

print(arr11)

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]


In [16]:
# create a 3D array with shape (2, 3, 4)
shape = (3, 2, 4)

arr12 = np.ones(shape, dtype='int')

print(arr12)

[[[1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]]]


In [17]:
# create a 3D array with shape (2, 3, 4)
shape = (2, 2, 4)

arr13 = np.empty(shape, dtype='int')

print(arr13)

[[[25895968444448860 23925768161198147 32370111954616435
   32088563961757788]
  [12948244072497268 32651616996819049 25896170311057512
   28710924373327984]]

 [[26740556586287209 27303510834217060 25896196080664693
   32651591226556520]
  [12948368627204207 29555336418492531 29836540811477108
   30962737072111727]]]


In [18]:
random_numbers = np.random.rand(3,3)  # Generates a 2x3 array of random numbers between 0 and 1
random_numbers

array([[0.29059479, 0.55664463, 0.6834319 ],
       [0.26032845, 0.36749351, 0.72943999],
       [0.72153797, 0.12923322, 0.21731581]])

In [19]:
random_numbers = np.random.randn(2, 3)  
random_numbers

array([[-0.04736398,  0.84374281,  0.00426836],
       [-0.24492891, -1.09779564,  0.59223077]])

In [20]:
random_integers = np.random.randint(-10, 10, size=(2, 3))  
random_integers

array([[ -9,  -7,  -3],
       [  9,   3, -10]], dtype=int32)

In [21]:
b = np.array([2,4,56,422,32,1])
b

array([  2,   4,  56, 422,  32,   1])

In [22]:
#to find the type
type(b)

numpy.ndarray

In [23]:
i = np.identity(2) 
i

array([[1., 0.],
       [0., 1.]])

In [24]:
diagonal_matrix = np.diag([1, 2, 3])
print(diagonal_matrix)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [25]:
np.diag([1,2])

array([[1, 0],
       [0, 2]])

In [26]:
x = np.array([1,2,3])
y = x 
z = np.copy(x)
print(x,y,z)


[1 2 3] [1 2 3] [1 2 3]


In [27]:
c = np.array([11,23,44], dtype = float)
c

array([11., 23., 44.])

In [28]:
g = c.astype('int')
g

array([11, 23, 44])

In [29]:
type(g[0])

numpy.int64

In [30]:
d = np.linspace(2,10,num=8, dtype=float)
d.astype(int)

array([ 2,  3,  4,  5,  6,  7,  8, 10])

In [31]:
re = np.arange(1,11)
re

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
re.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [33]:
re1 = np.arange(1,13).reshape(3,4)
re1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [34]:
re2 = np.arange(0,8).reshape(2,2,2)
re2

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [35]:
sh = np.arange(1,11).reshape(5,2)
sh.shape

(5, 2)

In [36]:
sh.size

10

In [37]:
sh

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [38]:
sh1 = np.arange(10)
sh1.shape

(10,)

In [39]:
sh2 = np.arange(8).reshape(2,2,2)
sh2.shape

(2, 2, 2)

In [40]:
si = np.arange(1,11).reshape(5,2)
si.size

10

In [41]:
len(si)

5

In [42]:
its = np.arange(1,13).reshape(4,3)
print(its)
its.itemsize 

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


8

In [43]:
its1 = np.linspace(0,10, num=10)
its1.itemsize

8

In [44]:
import numpy as np
so = np.arange(12).reshape(3,4)

In [45]:
so

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [46]:
so + 2 # -, *, /, **, %.

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [47]:
so - 2

array([[-2, -1,  0,  1],
       [ 2,  3,  4,  5],
       [ 6,  7,  8,  9]])

In [48]:
so * 2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [49]:
so % 2

array([[0, 1, 0, 1],
       [0, 1, 0, 1],
       [0, 1, 0, 1]])

In [50]:
ml = np.array([1,2,3,4,5,6,7,8,9,10])
ml1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
np.multiply(ml,ml1)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [51]:
np.divide(ml,ml1)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [52]:
ro = np.arange(12,24).reshape(3,4)
ro

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [53]:
ro > 20

array([[False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True]])

In [54]:
ro[ro > 20]

array([21, 22, 23])

In [55]:
ro[ro != 20]

array([12, 13, 14, 15, 16, 17, 18, 19, 21, 22, 23])

In [56]:
lo = np.array([[-1,2,7]])
lo1 = np.array([[4,5,6]])

comp = lo>lo1
comp

array([[False, False,  True]])

In [57]:
lo2 = np.array([True, False, True, False])
lo3 = np.array([True, True,False, False])

_and = np.logical_and(lo2, lo3)

_or = np.logical_or(lo2, lo3)
_and,_or

(array([ True, False, False, False]), array([ True,  True,  True, False]))

In [58]:
arr1 = np.array([1, 3, 7])
arr2 = np.array([2, 3, 6])


result_and = np.logical_and(arr1 > 2, arr2 > 2)
print(result_and)


result_or = np.logical_or(arr1 > 2, arr2 > 2)
print(result_or)

[False  True  True]
[False  True  True]


In [59]:
vo = np.array([1, 2, 3]) + 5
vo1 = np.array([4, 5, 6])

addition = vo + vo1
subtraction = vo - vo1
multiplication = vo * vo1
division = vo / vo1

print(vo)
print(addition,subtraction, multiplication, division)

[6 7 8]
[10 12 14] [2 2 2] [24 35 48] [1.5        1.4        1.33333333]


In [60]:
za = np.arange(12).reshape(3,4)
zb = np.arange(12, 24).reshape(3,4)
za, zb

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]))

In [61]:
addition = za + zb
subtraction = za - zb
multiplication = za * zb
print("Addition:\n", addition, "\n")

Addition:
 [[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]] 



In [62]:
Ao = np.random.random((3,3))
Ao

array([[0.65885424, 0.12198911, 0.2238784 ],
       [0.15785496, 0.48850313, 0.78243005],
       [0.84203672, 0.8218353 , 0.48187536]])

In [63]:
Ao*100

array([[65.88542449, 12.19891124, 22.38784044],
       [15.78549596, 48.8503135 , 78.24300532],
       [84.20367208, 82.18353012, 48.18753558]])

In [64]:
Ao = np.round(Ao*100)
Ao.astype('int')

array([[66, 12, 22],
       [16, 49, 78],
       [84, 82, 48]])

In [65]:
aa1 = np.sum(Ao, axis=0) #axis=1 represents rows , 0-columns
aa1

array([166., 143., 148.])

In [66]:
a1 = np.max(Ao)


a11 = np.max(Ao, axis=1)


a22 = np.min(Ao, axis=0)

a2 = np.min(Ao)

a3 = np.prod(Ao)


a1, a11, a22, a2, a3

(np.float64(84.0),
 array([66., 78., 84.]),
 array([16., 12., 22.]),
 np.float64(12.0),
 np.float64(352283987607552.0))

**Trignometric Finctions**

In [67]:
tf = np.arange(24, 36).reshape(3,4)
tf1 = np.arange(36,48).reshape(4,3)
tf

array([[24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35]])

In [68]:
np.sin(tf)

array([[-0.90557836, -0.13235175,  0.76255845,  0.95637593],
       [ 0.27090579, -0.66363388, -0.98803162, -0.40403765],
       [ 0.55142668,  0.99991186,  0.52908269, -0.42818267]])

In [69]:
np.cos(tf)

array([[ 0.42417901,  0.99120281,  0.64691932, -0.29213881],
       [-0.96260587, -0.74805753,  0.15425145,  0.91474236],
       [ 0.83422336, -0.01327675, -0.84857027, -0.90369221]])

In [70]:
np.tan(tf)

array([[ -2.1348967 ,  -0.13352641,   1.17875355,  -3.2737038 ],
       [ -0.2814296 ,   0.88714284,  -6.4053312 ,  -0.44169557],
       [  0.66100604, -75.3130148 ,  -0.62349896,   0.47381472]])

In [71]:
a = np.sin(180)
b = np.cos(45)
c= np.tan(45)

sec = 1/a
cosec = 1/b
cot = 1/np.tan(45)

sec

np.float64(-1.2482015977941976)

**Log and Exponent**

In [72]:
np.log(100)

np.float64(4.605170185988092)

In [73]:
np.exp(10)

np.float64(22026.465794806718)

In [74]:
np.sqrt(25)

np.float64(5.0)

In [75]:
np.power(2,3)

np.int64(8)

In [76]:
arr4 = np.array([10, 20, 30, 40, 50])
sqrt_result = np.sqrt(arr4)
print(sqrt_result)

[3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]


In [77]:
# Round to the nearest integer
arr = np.array([1.253, 2.753, 3.553, 4.953])
rounded_arr = np.round(arr,2)
print(rounded_arr) 

[1.25 2.75 3.55 4.95]


In [78]:
np.round(75.391, 2)

np.float64(75.39)

In [79]:
# Round to two decimals
arr = np.array([1.234, 2.567, 3.891])
rounded_arr = np.round(arr, decimals=2)
print(rounded_arr)

[1.23 2.57 3.89]


In [80]:
# Floor operation
arr = np.array([1.2, 2.7, 3.5, 4.9])
floored_arr = np.floor(arr)
print(floored_arr)

[1. 2. 3. 4.]


In [81]:
np.floor(np.random.random((2,3))*100) # gives the smallest integer

array([[37., 44., 94.],
       [ 3., 24., 36.]])

In [82]:
arr = np.array([1.2, 2.7, 3.5, 4.9])
ceiled_arr = np.ceil(arr)
print(ceiled_arr)

[2. 3. 4. 5.]


In [83]:
np.ceil(np.random.random((2,3))*100) # gives highest integer

array([[76., 35., 23.],
       [52., 43., 88.]])

In [84]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

In [85]:
np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [86]:
np.intersect1d(m,n)

array([3, 4, 5])

In [87]:
# Set difference
np.setdiff1d(m,n)

array([1, 2])

In [88]:
import numpy as np

idx = np.array([10, 20, 30, 40, 50])
first_element = idx[2]
sub_array = idx[1:4]
a = idx[-1]
first_element,sub_array,a

(np.int64(30), array([20, 30, 40]), np.int64(50))

In [89]:
p1 = np.arange(10)
p2 = np.arange(12).reshape(3,4)
p3 = np.arange(8).reshape(2,2,2)

In [90]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [91]:
p2[:,2]

array([ 2,  6, 10])

In [92]:
p2[:3:2, :]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [93]:
p3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [94]:
print(p3[1,0,1])

#Here first we take 0 because our desired is 0, is in first matrix which is 0 . and 1 row so 0 and first column so 0
p3[0,1,0]

5


np.int64(2)

In [95]:
p1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [96]:
p1[2:5]

array([2, 3, 4])

In [97]:
p1[2:5:2]

array([2, 4])

In [98]:
# fetching total First row
p2[0, :]

array([0, 1, 2, 3])

In [99]:
# fetching total third column
p2[:,2]

array([ 2,  6, 10])

In [100]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [101]:
p2[::2, ::3]

array([[ 0,  3],
       [ 8, 11]])

In [102]:
#3D Slicing
p3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [103]:
p3[0,1,:] 

array([2, 3])

In [104]:
p3[1,:,1]

array([5, 7])

In [105]:
import numpy as np
i = np.array([10,20,30,110])
items = [10,20,30,40,50,60,70,80,90,100]
np.isin(i,items)

array([ True,  True,  True, False])

In [106]:
i[np.isin(i,items)]

array([10, 20, 30])

In [107]:
np.isin(10, items)

array(True)

In [108]:
arr = np.array([[1, 3, 5],[8, 2, 4]]).reshape(3, 2)

print(arr)

max_index = np.argmax(arr)
print("Index of maximum value:", max_index)

max_indices_col = np.argmax(arr, axis=1)
print("Indices of maximum values along each column:", max_indices_col)

[[1 3]
 [5 8]
 [2 4]]
Index of maximum value: 3
Indices of maximum values along each column: [1 1 1]


In [109]:
import numpy as np

arr = np.array([[1, 3, 5],
                [8, 2, 4]]).reshape(2, 3)

print(arr)

min_index = np.argmin(arr)
print("Index of minimum value:", min_index)

min_indices_row = np.argmin(arr, axis=1)
print("Indices of minimum values along each row:", min_indices_row)

[[1 3 5]
 [8 2 4]]
Index of minimum value: 0
Indices of minimum values along each row: [0 1]


In [110]:
wh = np.arange(1,101)
print(wh)
np.where(wh>50)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


(array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
        67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
        84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]),)

In [111]:
# replace all values > 50 with 0
np.where(wh>50,1,wh)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1])

**Sorting**

In [112]:
s = np.random.randint(1,100,15)
s1 = np.random.randint(1,100,24).reshape(6,4)
s , s1

(array([67, 91, 88, 74, 94, 85, 36, 19, 89, 12, 41, 18, 15, 70, 49],
       dtype=int32),
 array([[56, 97, 64, 44],
        [60, 85, 63, 72],
        [99, 66, 86, 18],
        [14,  7, 66, 12],
        [85, 19,  8, 56],
        [96, 12, 84, 91]], dtype=int32))

In [113]:
g = np.sort(s)
g

array([12, 15, 18, 19, 36, 41, 49, 67, 70, 74, 85, 88, 89, 91, 94],
      dtype=int32)

In [114]:
np.sort(s)[::-1] 

array([94, 91, 89, 88, 85, 74, 70, 67, 49, 41, 36, 19, 18, 15, 12],
      dtype=int32)

In [115]:
np.sort(s1)

array([[44, 56, 64, 97],
       [60, 63, 72, 85],
       [18, 66, 86, 99],
       [ 7, 12, 14, 66],
       [ 8, 19, 56, 85],
       [12, 84, 91, 96]], dtype=int32)

In [116]:
np.sort(s1, axis=0) 

array([[14,  7,  8, 12],
       [56, 12, 63, 18],
       [60, 19, 64, 44],
       [85, 66, 66, 56],
       [96, 85, 84, 72],
       [99, 97, 86, 91]], dtype=int32)

**Appending**

In [117]:
np.append(s1,1)

array([56, 97, 64, 44, 60, 85, 63, 72, 99, 66, 86, 18, 14,  7, 66, 12, 85,
       19,  8, 56, 96, 12, 84, 91,  1])

In [118]:
np.ones((4,1), dtype=int)

array([[1],
       [1],
       [1],
       [1]])

In [119]:
# adding one row to 2d arrary
np.append(s1,np.ones((6,1))).astype('int')

array([56, 97, 64, 44, 60, 85, 63, 72, 99, 66, 86, 18, 14,  7, 66, 12, 85,
       19,  8, 56, 96, 12, 84, 91,  1,  1,  1,  1,  1,  1])

In [120]:
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [121]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

**Dot Product**

In [122]:
dp = np.array([[1,2],[3,4]])
dp1 = np.array([[5,6],[7,8]])
print(dp)
print(dp1)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [123]:
c = np.dot(dp,dp1)
c

array([[19, 22],
       [43, 50]])

In [124]:
A = np.array([[11, 12], [13, 14]])
B = np.array([[15, 16], [17, 18]])
dot_product = np.dot(A, B)
dot_product

array([[369, 392],
       [433, 460]])

**Percentaile**

In [125]:
s = np.array([90,10,20,30,40,50,60,70,80,100])
np.percentile(s, 100)

np.float64(100.0)

In [126]:
a = np.random.randint(1,100,16)
b = np.random.randint(1,100,24).reshape(6,4)

In [127]:
np.sort(a)

array([ 3, 16, 17, 19, 25, 58, 59, 63, 63, 63, 63, 88, 92, 93, 94, 98],
      dtype=int32)

In [128]:
np.percentile(a,100) #max

np.float64(98.0)

In [129]:
np.percentile(a,0) # min

np.float64(3.0)

In [130]:
np.percentile(a,50) #median

np.float64(63.0)

In [131]:
np.percentile(a,25) 

np.float64(23.5)

In [132]:
np.percentile(a,75) 

np.float64(89.0)

**Array Manipulation:**

In [133]:
am = np.arange(12).reshape(3,4)
am

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [134]:
np.transpose(am)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [135]:
am.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [136]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
transposed_arr = np.transpose(arr)
arr,transposed_arr

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[1, 4],
        [2, 5],
        [3, 6]]))

In [137]:
ra = np.arange(12).reshape(3,4)
ra

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [138]:
ra.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [139]:
ra1 = np.arange(0,8).reshape(2,2,2)
ra1

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [140]:
np.ravel(ra1)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [141]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
flattened_arr = arr.flatten()
flattened_arr

array([1, 2, 3, 4, 5, 6])

In [142]:
ra.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [143]:
ra1.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7])

**Array Concatenation** 

In [144]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[5,6,4],[5,6,1]])
print(arr)
print(arr2)
concate = np.concatenate((arr,arr2),axis=1)
concate

[[1 2 3]
 [4 5 6]]
[[5 6 4]
 [5 6 1]]


array([[1, 2, 3, 5, 6, 4],
       [4, 5, 6, 5, 6, 1]])