**Numpy**

In [ ]:
import numpy as np

In [ ]:
arr1 = np.arange(0, 15, 3, dtype='int') 
arr1

array([ 0,  3,  6,  9, 12])

In [ ]:
arr2 = np.linspace(0, 10, num=4, dtype='int', endpoint=False)
arr2

array([0, 2, 5, 7])

In [ ]:
a = np.linspace(0,20, 10, endpoint=False, dtype='int')
a

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
arr3 = np.array([5, 8, 12])
print(arr3)

[ 5  8 12]


In [ ]:
arr3.shape

(3,)

In [ ]:
arr4 = np.arange(5, 14, 2)

print(arr4)

[ 5  7  9 11 13]


In [ ]:
arr5 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arr5)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
arr5.shape

(3, 4)

In [ ]:
arr6 = np.zeros((3,4), dtype=float)
print(arr6)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
shape = (3, 4)
arr7 = np.ones(shape, dtype='int')
print(arr7)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [ ]:
# create a 2D array with shape (3, 4)
arr8 = np.empty((3,4), dtype=int)
print(arr8)

[[      2939742534936                  50                   0
                    0]
 [  29555310641283072 7146768841584043371 3257569520544657716
  4063148658377777765]
 [3975888164340968803 3990863481760080694 8386112019186069602
  3544951258285634421]]


In [ ]:
# create a 3D array with shape (2, 3, 4)
nested_list = [[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],

[[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]

arr9 = np.array(nested_list)

print(arr9)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [ ]:
arr9.shape

(2, 3, 4)

In [ ]:
# create a 3D array with shape (2, 3, 4)
shape = (2, 3, 4)

arr11 = np.zeros(shape, dtype='int')

print(arr11)

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]


In [ ]:
# create a 3D array with shape (2, 3, 4)
shape = (3, 2, 4)

arr12 = np.ones(shape, dtype='int')

print(arr12)

[[[1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]]]


In [ ]:
# create a 3D array with shape (2, 3, 4)
shape = (2, 2, 4)

arr13 = np.empty(shape, dtype='int')

print(arr13)

[[[25895968444448860 23925768161198147 32370111954616435
   30681201962451036]
  [12948244072890473 32651616996819049 25896170311057512
   28710924373327984]]

 [[26740556586287209 27303510834217060 25896196080664693
   32651591226556520]
  [12948368627204207 29555336418492531 29836540811477108
   30962737072111727]]]


In [ ]:
random_numbers = np.random.rand(3,3)  # Generates a 2x3 array of random numbers between 0 and 1
random_numbers

array([[0.41371236, 0.67211894, 0.29177303],
       [0.69231484, 0.56554084, 0.50765447],
       [0.06018599, 0.2490662 , 0.49719274]])

In [ ]:
random_numbers = np.random.randn(2, 3)  # Generates a 2x3 array of random numbers from a standard normal distribution
random_numbers

array([[-0.45932605, -1.53868435,  0.87570512],
       [ 0.24617333, -0.00736535, -0.20847847]])

In [ ]:
random_integers = np.random.randint(-10, 10, size=(2, 3))  # Generates a 2x3 array of random integers between 1 (inclusive) and 10 (exclusive)
random_integers

array([[ -1,  -7,  -9],
       [-10,  -1,   3]], dtype=int32)

In [ ]:
b = np.array([2,4,56,422,32,1])
b

array([  2,   4,  56, 422,  32,   1])

In [ ]:
#to find the type
type(b)

numpy.ndarray

In [ ]:
i = np.identity(2) #indentity matrix is that diagonal items will be ones and evrything will be zeros
i

array([[1., 0.],
       [0., 1.]])

In [ ]:
diagonal_matrix = np.diag([1, 2, 3])
print(diagonal_matrix)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [ ]:
np.diag([1,2])

array([[1, 0],
       [0, 2]])

In [ ]:
x = np.array([1,2,3])
y = x 
z = np.copy(x)
print(x,y,z)


[1 2 3] [1 2 3] [1 2 3]


In [ ]:
c = np.array([11,23,44], dtype = float)
c

array([11., 23., 44.])

In [ ]:
g = c.astype('int')
g

array([11, 23, 44])

In [ ]:
type(g[0])

numpy.int64

In [ ]:
d = np.linspace(2,10,num=8, dtype=float)
d.astype(int)

array([ 2,  3,  4,  5,  6,  7,  8, 10])

In [ ]:
re = np.arange(1,11)
re

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
re.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [ ]:
re1 = np.arange(1,13).reshape(3,4)
re1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
re2 = np.arange(0,8).reshape(2,2,2)
re2

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
sh = np.arange(1,11).reshape(5,2)
sh.shape

(5, 2)

In [ ]:
sh.size

10

In [ ]:
sh

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [ ]:
sh1 = np.arange(10)
sh1.shape

(10,)

In [ ]:
sh2 = np.arange(8).reshape(2,2,2)
sh2.shape

(2, 2, 2)

In [ ]:
si = np.arange(1,11).reshape(5,2)
si.size

10

In [ ]:
len(si) # No of rows

5

In [ ]:
its = np.arange(1,13).reshape(4,3)
print(its)
its.itemsize #Memory occupied by the item

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


8

In [ ]:
its1 = np.linspace(0,10, num=10)
its1.itemsize

8

In [ ]:
import numpy as np
so = np.arange(12).reshape(3,4)

In [ ]:
so

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
so + 2 # -, *, /, **, %.

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [ ]:
so - 2

array([[-2, -1,  0,  1],
       [ 2,  3,  4,  5],
       [ 6,  7,  8,  9]])

In [ ]:
so * 2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [ ]:
so % 2

array([[0, 1, 0, 1],
       [0, 1, 0, 1],
       [0, 1, 0, 1]])

In [ ]:
ml = np.array([1,2,3,4,5,6,7,8,9,10])
ml1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
np.multiply(ml,ml1)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [ ]:
np.divide(ml,ml1)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
ro = np.arange(12,24).reshape(3,4)
ro

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
ro > 20

array([[False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True]])

In [ ]:
ro[ro > 20]

array([21, 22, 23])

In [ ]:
ro[ro != 20]

array([12, 13, 14, 15, 16, 17, 18, 19, 21, 22, 23])

In [ ]:
lo = np.array([[-1,2,7]])
lo1 = np.array([[4,5,6]])

comp = lo>lo1
comp

array([[False, False,  True]])

In [ ]:
lo2 = np.array([True, False, True, False])
lo3 = np.array([True, True,False, False])

_and = np.logical_and(lo2, lo3)

_or = np.logical_or(lo2, lo3)
_and,_or

(array([ True, False, False, False]), array([ True,  True,  True, False]))

In [ ]:
arr1 = np.array([1, 3, 7])
arr2 = np.array([2, 3, 6])

# Logical AND where both conditions are True (e.g., arr1 > 2 and arr2 > 2)
result_and = np.logical_and(arr1 > 2, arr2 > 2)
print(result_and)

# Logical OR where either condition is True (e.g., arr1 > 2 or arr2 > 2)
result_or = np.logical_or(arr1 > 2, arr2 > 2)
print(result_or)

[False  True  True]
[False  True  True]


In [ ]:
vo = np.array([1, 2, 3]) + 5
vo1 = np.array([4, 5, 6])

addition = vo + vo1
subtraction = vo - vo1
multiplication = vo * vo1
division = vo / vo1

print(vo)
print(addition,subtraction, multiplication, division)

[6 7 8]
[10 12 14] [2 2 2] [24 35 48] [1.5        1.4        1.33333333]


In [ ]:
za = np.arange(12).reshape(3,4)
zb = np.arange(12, 24).reshape(3,4)
za, zb

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]))

In [ ]:
addition = za + zb
subtraction = za - zb
multiplication = za * zb
print("Addition:\n", addition, "\n")

Addition:
 [[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]] 



In [ ]:
Ao = np.random.random((3,3))
Ao

array([[0.62449793, 0.70274815, 0.62781062],
       [0.59782948, 0.51592789, 0.25898947],
       [0.88667881, 0.86769168, 0.12901756]])

In [ ]:
Ao*100

array([[62.44979328, 70.27481481, 62.78106202],
       [59.78294773, 51.5927892 , 25.89894703],
       [88.66788117, 86.7691678 , 12.90175629]])

In [ ]:
Ao = np.round(Ao*100)
Ao.astype('int')

array([[62, 70, 63],
       [60, 52, 26],
       [89, 87, 13]])

In [ ]:
aa1 = np.sum(Ao, axis=0) #axis=1 represents rows , 0-columns
aa1

array([211., 209., 102.])

In [ ]:
a1 = np.max(Ao)

# if we want maximum of every row
a11 = np.max(Ao, axis=1)

# # maximum of every column
a22 = np.min(Ao, axis=0)

a2 = np.min(Ao)

a3 = np.prod(Ao) #Multiplication


a1, a11, a22, a2, a3

(np.float64(89.0),
 array([70., 60., 89.]),
 array([60., 52., 13.]),
 np.float64(13.0),
 np.float64(2232599548233600.0))

**Trignometric Finctions**

In [ ]:
tf = np.arange(24, 36).reshape(3,4)
tf1 = np.arange(36,48).reshape(4,3)
tf

array([[24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35]])

In [ ]:
np.sin(tf)

array([[-0.90557836, -0.13235175,  0.76255845,  0.95637593],
       [ 0.27090579, -0.66363388, -0.98803162, -0.40403765],
       [ 0.55142668,  0.99991186,  0.52908269, -0.42818267]])

In [ ]:
np.cos(tf)

array([[ 0.42417901,  0.99120281,  0.64691932, -0.29213881],
       [-0.96260587, -0.74805753,  0.15425145,  0.91474236],
       [ 0.83422336, -0.01327675, -0.84857027, -0.90369221]])

In [ ]:
np.tan(tf)

array([[ -2.1348967 ,  -0.13352641,   1.17875355,  -3.2737038 ],
       [ -0.2814296 ,   0.88714284,  -6.4053312 ,  -0.44169557],
       [  0.66100604, -75.3130148 ,  -0.62349896,   0.47381472]])

In [ ]:
a = np.sin(180)
b = np.cos(45)
c= np.tan(45)

sec = 1/a
cosec = 1/b
cot = 1/np.tan(45)

sec

np.float64(-1.2482015977941976)

**Log and Exponent**

In [ ]:
np.log(100)

np.float64(4.605170185988092)

In [ ]:
np.exp(10)

np.float64(22026.465794806718)

In [ ]:
np.sqrt(25)

np.float64(5.0)

In [ ]:
np.power(2,3)

np.int64(8)

In [ ]:
arr4 = np.array([10, 20, 30, 40, 50])
sqrt_result = np.sqrt(arr4)
print(sqrt_result)

[3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]


In [ ]:
# Round to the nearest integer
arr = np.array([1.253, 2.753, 3.553, 4.953])
rounded_arr = np.round(arr,2)
print(rounded_arr) 

[1.25 2.75 3.55 4.95]


In [ ]:
np.round(75.391, 2)

np.float64(75.39)

In [ ]:
# Round to two decimals
arr = np.array([1.234, 2.567, 3.891])
rounded_arr = np.round(arr, decimals=2)
print(rounded_arr)

[1.23 2.57 3.89]


In [ ]:
# Floor operation
arr = np.array([1.2, 2.7, 3.5, 4.9])
floored_arr = np.floor(arr)
print(floored_arr)

[1. 2. 3. 4.]


In [ ]:
np.floor(np.random.random((2,3))*100) # gives the smallest integer

array([[68., 85., 34.],
       [57., 84., 33.]])

In [ ]:
arr = np.array([1.2, 2.7, 3.5, 4.9])
ceiled_arr = np.ceil(arr)
print(ceiled_arr)

[2. 3. 4. 5.]


In [ ]:
np.ceil(np.random.random((2,3))*100) # gives highest integer

array([[52., 24., 76.],
       [23., 32., 69.]])

In [ ]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

In [ ]:
np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
np.intersect1d(m,n)

array([3, 4, 5])

In [ ]:
# Set difference
np.setdiff1d(m,n)

array([1, 2])

In [ ]:
import numpy as np

idx = np.array([10, 20, 30, 40, 50])
first_element = idx[2]
sub_array = idx[1:4]
a = idx[-1]
first_element,sub_array,a

(np.int64(30), array([20, 30, 40]), np.int64(50))

In [ ]:
p1 = np.arange(10)
p2 = np.arange(12).reshape(3,4)
p3 = np.arange(8).reshape(2,2,2)

In [ ]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
p2[:,2]

array([ 2,  6, 10])

In [ ]:
p2[:3:2, :]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [ ]:
p3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
print(p3[1,0,1])

#Here first we take 0 because our desired is 0, is in first matrix which is 0 . and 1 row so 0 and first column so 0
p3[0,1,0]

5


np.int64(2)

In [ ]:
p1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
p1[2:5]

array([2, 3, 4])

In [ ]:
p1[2:5:2]

array([2, 4])

In [ ]:
# fetching total First row
p2[0, :]

array([0, 1, 2, 3])

In [ ]:
# fetching total third column
p2[:,2]

array([ 2,  6, 10])

In [ ]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
p2[::2, ::3]

array([[ 0,  3],
       [ 8, 11]])

In [ ]:
#3D Slicing
p3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
p3[0,1,:] 

array([2, 3])

In [ ]:
p3[1,:,1]

array([5, 7])

In [ ]:
import numpy as np
i = np.array([10,20,30,110])
items = [10,20,30,40,50,60,70,80,90,100]
np.isin(i,items)

array([ True,  True,  True, False])

In [ ]:
i[np.isin(i,items)]

array([10, 20, 30])

In [ ]:
np.isin(10, items)

array(True)

In [ ]:
# Create a 2D array
arr = np.array([[1, 3, 5],[8, 2, 4]]).reshape(3, 2)

print(arr)

# Find the index of the maximum value in the entire array
max_index = np.argmax(arr)
print("Index of maximum value:", max_index)

# Find the indices of the maximum values along each column
max_indices_col = np.argmax(arr, axis=1)
print("Indices of maximum values along each column:", max_indices_col)

[[1 3]
 [5 8]
 [2 4]]
Index of maximum value: 3
Indices of maximum values along each column: [1 1 1]


In [ ]:
import numpy as np

# Create a 2D array
arr = np.array([[1, 3, 5],
                [8, 2, 4]]).reshape(2, 3)

print(arr)

# Find the index of the minimum value in the entire array
min_index = np.argmin(arr)
print("Index of minimum value:", min_index)

# Find the indices of the minimum values along each row
min_indices_row = np.argmin(arr, axis=1)
print("Indices of minimum values along each row:", min_indices_row)

[[1 3 5]
 [8 2 4]]
Index of minimum value: 0
Indices of minimum values along each row: [0 1]


In [ ]:
wh = np.arange(1,101)
print(wh)
np.where(wh>50)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


(array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
        67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
        84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]),)

In [ ]:
# replace all values > 50 with 0
np.where(wh>50,1,wh)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1])

**Sorting**

In [ ]:
s = np.random.randint(1,100,15)
s1 = np.random.randint(1,100,24).reshape(6,4)
s , s1

(array([88, 47, 64, 24, 24,  9, 46, 11, 60, 99, 34, 45,  6, 28, 19],
       dtype=int32),
 array([[35, 83,  3, 11],
        [40, 83, 70, 52],
        [42, 48, 22, 80],
        [11,  9, 85, 10],
        [ 8, 46, 43, 50],
        [80, 44, 14, 68]], dtype=int32))

In [ ]:
g = np.sort(s)
g

array([ 6,  9, 11, 19, 24, 24, 28, 34, 45, 46, 47, 60, 64, 88, 99],
      dtype=int32)

In [ ]:
np.sort(s)[::-1] #Descending

array([99, 88, 64, 60, 47, 46, 45, 34, 28, 24, 24, 19, 11,  9,  6],
      dtype=int32)

In [ ]:
np.sort(s1)

array([[ 3, 11, 35, 83],
       [40, 52, 70, 83],
       [22, 42, 48, 80],
       [ 9, 10, 11, 85],
       [ 8, 43, 46, 50],
       [14, 44, 68, 80]], dtype=int32)

In [ ]:
np.sort(s1, axis=0) #Column wise sorting

array([[ 8,  9,  3, 10],
       [11, 44, 14, 11],
       [35, 46, 22, 50],
       [40, 48, 43, 52],
       [42, 83, 70, 68],
       [80, 83, 85, 80]], dtype=int32)

**Appending**

In [ ]:
np.append(s1,1)

array([35, 83,  3, 11, 40, 83, 70, 52, 42, 48, 22, 80, 11,  9, 85, 10,  8,
       46, 43, 50, 80, 44, 14, 68,  1])

In [ ]:
np.ones((4,1), dtype=int)

array([[1],
       [1],
       [1],
       [1]])

In [ ]:
# adding one row to 2d arrary
np.append(s1,np.ones((6,1))).astype('int')

array([35, 83,  3, 11, 40, 83, 70, 52, 42, 48, 22, 80, 11,  9, 85, 10,  8,
       46, 43, 50, 80, 44, 14, 68,  1,  1,  1,  1,  1,  1])

In [ ]:
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [ ]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

**Dot Product**

In [ ]:
dp = np.array([[1,2],[3,4]])
dp1 = np.array([[5,6],[7,8]])
print(dp)
print(dp1)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [ ]:
c = np.dot(dp,dp1)
c

array([[19, 22],
       [43, 50]])

In [ ]:
A = np.array([[11, 12], [13, 14]])
B = np.array([[15, 16], [17, 18]])
dot_product = np.dot(A, B)
dot_product

array([[369, 392],
       [433, 460]])

**Percentaile**

In [ ]:
s = np.array([90,10,20,30,40,50,60,70,80,100])
np.percentile(s, 100)

np.float64(100.0)

In [ ]:
a = np.random.randint(1,100,16)
b = np.random.randint(1,100,24).reshape(6,4)

In [ ]:
np.sort(a)

array([17, 26, 29, 32, 38, 43, 43, 44, 44, 54, 72, 75, 81, 86, 88, 93],
      dtype=int32)

In [ ]:
np.percentile(a,100) #max

np.float64(93.0)

In [ ]:
np.percentile(a,0) # min

np.float64(17.0)

In [ ]:
np.percentile(a,50) #median

np.float64(44.0)

In [ ]:
np.percentile(a,25) 

np.float64(36.0)

In [ ]:
np.percentile(a,75) 

np.float64(77.5)

**Array Manipulation:**

In [ ]:
am = np.arange(12).reshape(3,4)
am

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
np.transpose(am)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [ ]:
am.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
transposed_arr = np.transpose(arr)
arr,transposed_arr

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[1, 4],
        [2, 5],
        [3, 6]]))

In [ ]:
ra = np.arange(12).reshape(3,4)
ra

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
ra.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
ra1 = np.arange(0,8).reshape(2,2,2)
ra1

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
np.ravel(ra1)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
flattened_arr = arr.flatten()
flattened_arr

array([1, 2, 3, 4, 5, 6])

In [ ]:
ra.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
ra1.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7])

**Array Concatenation** 

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[5,6,4],[5,6,1]])
print(arr)
print(arr2)
concate = np.concatenate((arr,arr2),axis=1)
concate

[[1 2 3]
 [4 5 6]]
[[5 6 4]
 [5 6 1]]


array([[1, 2, 3, 5, 6, 4],
       [4, 5, 6, 5, 6, 1]])